FROM python:3.8

RUN apt-get update && apt-get install -y libgl1-mesa-glx

WORKDIR /app

COPY ./processor/requirements.txt .
COPY ./processor .

RUN pip install -r requirements.txt
CMD ["python", "-u","./processor_src/processor.py"]

