FROM python:3.8

RUN apt-get update && apt-get install -y libgl1-mesa-glx

WORKDIR /app

COPY ./reader/requirements.txt .
COPY ./reader .

RUN pip install -r requirements.txt
CMD ["python", "-u","./reader_src/reader.py"]
