FROM nvidia/cuda:12.2.0-base-ubuntu22.04 AS base
CMD nvidia-smi

FROM python:3.8

RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y curl
RUN apt-get install unzip
RUN apt-get -y install python3
RUN apt-get -y install python3-pip

WORKDIR /app

COPY ./detector/requirements.txt .
COPY ./detector .

RUN pip3 install -r requirements.txt

CMD ["python3", "-u", "./detector_src/detector.py"]
